inherit_from: .rubocop_todo.yml

Lint/LiteralInCondition:
  Enabled: true
Lint/StringConversionInInterpolation:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true

# These cops want parentheses that really aren't necessary
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# This cop gives false positives for Cucumber steps that aren't used.
Lint/Debugger:
  Enabled: false

# What else am I supposed to call the block variable when using find or each_with_object?
Lint/ShadowingOuterLocalVariable:
  Enabled: false
