inherit_from: .rubocop_todo.yml

# This cop reports operator usages that are correct and not ambiguous.
Lint/AmbiguousOperator:
  Enabled: false

# This cop gives false positives for Cucumber steps that aren't used.
Lint/Debugger:
  Enabled: false
