inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/*
    - config/boot.rb
    - config/environment.rb
    - config.ru
    - db/schema.rb
    - features/support/env.rb
    - lib/tasks/cucumber.rake
    - spec/spec_helper.rb

# Customized cops

Layout/CaseIndentation:
  IndentOneStep: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Naming/MethodParameterName:
  MinNameLength: 1

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/FormatString:
  EnforcedStyle: percent

Style/NumericLiterals:
  MinDigits: 12

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '()'
    '%w': '()'
    '%W': '()'

Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Disabled cops

Layout/ArgumentAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

# Gives false positives for Cucumber steps that aren't used
Lint/Debugger:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

# What else am I supposed to call the block variable when using find or each_with_object?
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Objects to a usage needed to implement OAuth signing
Lint/UriEscapeUnescape:
  Enabled: false

Metrics:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*.rb'

Style/AccessModifierDeclarations:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IfWithBooleanLiteralBranches:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
# Gives false positive on Cucumber step definitions
Style/RegexpLiteral:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/WordArray:
  Enabled: false
