# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   There is no gem for Windows.  Install mysql.so from RubyForApache.
#   http://rubyforge.org/projects/rubyforapache
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
# Copy this file to database.yml in the same directory, and

defaults: &defaults
    adapter:  mysql
    username:  # <-- put your database username here
    password:  # <-- put your database password here
    host:     localhost

development:
  database: gww_dev
  <<: *defaults

test:
  database: gww_test
  <<: *defaults

production:
  database: gww_production
  <<: *defaults
