# Copy this file to database.yml in the same directory, and

defaults: &defaults
  adapter:   mysql2
  host:      localhost

development:
  database: gww_dev
  username: gww_dev
  password:  # <-- put your development database password here
  <<: *defaults

test:
  database: gww_test
  username: gww_dev
  password:  # <-- put your test database password here
  <<: *defaults

production:
  database: gww_production
  username: gww_production
  password:  # <-- put your production database password here
  <<: *defaults
