# Copy this file to database.yml in the same directory, remove the environments you don't need on this machine, and

defaults: &defaults
  adapter: mysql2spatial
  host: localhost
  encoding: utf8mb4
  pool: 5

development:
  <<: *defaults
  database: gww_dev
  username: gww_dev
  password:  # <-- put your development database password here

test:
  <<: *defaults
  database: gww_test
  username: gww_dev
  password:  # <-- put your test database password here

production:
  <<: *defaults
  database: gww_production
  username: gww_production
  password:  # <-- put your production database password here
