# Copy this file to flickr_credentials.yml in the same directory, and
flickr_credentials:
  secret:  # <-- put your secret here
  api_key:  # <-- put your API key here
  oauth_token:  # <-- put your oauth token here
  oauth_token_secret:  # <-- put your oauth token secret here
  score_topic_url:  # <-- put the URL of the discussion topic where score reports are posted here
