# Copy this file to flickr_credentials.yml in the same directory, and
flickr_credentials:
  secret:  # <-- put your secret here
  api_key:  # <-- put your API key here
  auth_token:  # <-- put your auth token here
  score_topic_url:  # <-- put the URL of the discussion topic where score reports are posted here
