#!/bin/sh
`dirname $0`/drop_sfgis $1 $2 $3
ogr2ogr -f MySQL MYSQL:$1,user=$2,host=localhost,password=$3 -t_srs EPSG:4326 `dirname $0`/../../sfgis/stclines/StClines.shp
ogr2ogr -f MySQL MYSQL:$1,user=$2,host=localhost,password=$3 -t_srs EPSG:4326 `dirname $0`/../../sfgis/stnodes/StNodes.shp
ogr2ogr -f MySQL MYSQL:$1,user=$2,host=localhost,password=$3 -t_srs EPSG:4326 `dirname $0`/../../sfgis/stintersections/StIntersections.shp
