#!/bin/sh -el
# The above line makes this a login shell so that e.g. rbenv
# (which is normally initialized in .bashrc) is initialized.

# This script updates production GWW from github. It's only meant for
# production; it does things that are only relevant in the production
# environment.

cd `dirname $0`/..
script/down
git fetch --tags
git checkout `git tag | ruby -e 'puts STDIN.readlines.sort_by { |s| s[6, s.length - 6].to_i }.last'`
bundle install --deployment --without test
bundle exec rake RAILS_ENV=production db:migrate assets:precompile
touch tmp/restart.txt
rm -rf public/cache
mkdir public/cache
script/up
