name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Test
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true
          cache-version: 2
        env:
          BUNDLE_WITHOUT: production
      - run: mysql --version # the default runner currently includes 8.0.39
      - run: sudo systemctl start mysql
      - run: mysql -uroot -proot < db/create-user.sql
      - name: Run tests
        run: bundle exec rake db:create db:structure:load db:schema:dump default
        env:
          RAILS_ENV: test
          DATABASE_HOST: localhost
          DATABASE_PASSWORD: gww_dev
          FLICKR_SECRET: ${{secrets.FLICKR_SECRET}}
          FLICKR_API_KEY: ${{secrets.FLICKR_API_KEY}}
          FLICKR_OAUTH_TOKEN: ${{secrets.FLICKR_OAUTH_TOKEN}}
          FLICKR_OAUTH_TOKEN_SECRET: ${{secrets.FLICKR_OAUTH_TOKEN_SECRET}}
          FLICKR_GROUP_ID: 32053327@N00
          FLICKR_SCORE_TOPIC_URL: https://www.flickr.com/groups/guesswheresf/discuss/72157633043621593/
          GOOGLE_MAPS_API_KEY: ${{secrets.GOOGLE_MAPS_API_KEY}}

      - name: Tag
        uses: actions/github-script@v7
        with:
          script: |
            const buildTags =
              await github.rest.git.listMatchingRefs({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/build-'
              })
            const previousSuccessfulBuildNumber =
              buildTags
                .data.map(tag => parseInt(tag.ref.split('-')[1]))
                .reduce((largest_so_far, n) => Math.max(largest_so_far, n), 0)
            const newBuildTag = `build-${previousSuccessfulBuildNumber + 1}`
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              ref: `refs/tags/${newBuildTag}`
            })
            console.log(`Tagged ${context.sha} ${newBuildTag}`)

      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          cat >>~/.ssh/config <<END
          Host *
              CheckHostIP no
              StrictHostKeyChecking no
              UseRoaming no
          END
          echo "${{secrets.DEPLOY_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh ec2-user@guesswheresf.org lib/gww/script/update-and-restart
